spring:
  servlet:
    multipart:
      max-file-size: -1
  datasource:
    url: jdbc:mariadb://localhost:3306/security?autoReconnect=true&amp;autoReconnectForPools=true
    username: root
    password: wltd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  type-aliases-package: com.wltd.bean
  mapper-locations: classpath*:com/wltd/mapper/*.xml
  configuration:
    cache-enabled: true

logging:
  level:
    root: INFO
    com:
      wltd:
        mapper: debug
  file: logs/service-security.log